[build]
publish = "public"
command = "HUGO_ENV=production hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.63.1"
HUGO_ENV = "production"
#HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "HUGO_ENV=staging hugo --gc --minify -b $DEPLOY_PRIME_URL"
